# Generated by Django 3.2.3 on 2021-06-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_factura_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='precio_unitario',
            field=models.PositiveIntegerField(),
        ),
    ]
