# Generated by Django 3.2.3 on 2021-06-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_auto_20210617_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='anio',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='precio_unitario',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
