# Generated by Django 3.2.3 on 2021-06-27 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_auto_20210617_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineafactura',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.factura'),
        ),
    ]
